# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5.2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cx_Oracle
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_MainWindow_5_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777210))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 48))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Запрос 5.2"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">5.2.</span><span style=\" font-size:9pt;\"> Получить сведения о наличии гаражного хозяйства по каждой категории транспорта</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Ничего не найдено"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Тип объекта"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Марка авто"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Тип авто"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Выберете нужный тип транспорта"))
        self.comboBox.setItemText(1, _translate("MainWindow", "укпувып"))
        self.comboBox.setItemText(2, _translate("MainWindow", "вапыва"))
        self.comboBox.setItemText(3, _translate("MainWindow", "ывапыв"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))

        self.pushButton.clicked.connect(self.select_search)   
        self.search_type()

    def search_type(self):
        _translate = QtCore.QCoreApplication.translate
        dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='orcl') 
        conn = cx_Oracle.connect(user='test', password='111', dsn=dsn_tns) 

        mycursor = conn.cursor()
        mycursor.execute(str(open('5.2_.txt').read().split(';')[0]).encode().decode('utf8').encode('cp1251').decode('utf8')) 
        result = mycursor.fetchall()
        #print(result)
        row_count = mycursor.rowcount

        if row_count == 0:
            self.label.setText(_translate("MainWindow", "Не найдено ни одного типа транспорта"))
        else:
            self.label.setText(_translate("MainWindow", "Найдено " + str(row_count) + " типов тарнспорта. Выберете один из них."))
            for row_number, row_data in enumerate(result):
                #self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    data_str = str(data)
                    if self.comboBox.count() < int(row_count) + 1:
                        self.comboBox.addItem("")
                    self.comboBox.setItemText(row_number + 1, _translate("MainWindow", data_str))
        mycursor.close()
        conn.close()

    def select_search(self):
        dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='orcl') 
        conn = cx_Oracle.connect(user='test', password='111', dsn=dsn_tns) 
        mycursor = conn.cursor()
        
        if self.comboBox.currentText() == "Выберете нужный тип транспорта":
            self.search_type()
        else:
            type_car = self.comboBox.currentText()
            mycursor.execute(str(open('5.2.txt').read().split(';')[0]).encode().decode('utf8').encode('cp1251').decode('utf8').format(type_car)) 
            result = mycursor.fetchall()

            if mycursor.rowcount > 0:
                self.label.setText(QtCore.QCoreApplication.translate("MainWindow", str(mycursor.rowcount) + " строк найдено по категории: " + type_car))
            else:
                self.label.setText(QtCore.QCoreApplication.translate("MainWindow", "Ничего не найдено по категории: " + type_car))
            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    data_str = str(data)
                    if data_str == "None":
                        data_str = ""
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(data_str))

        mycursor.close()
        conn.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_5_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
