# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cx_Oracle
from PyQt5.QtWidgets import QTableWidgetItem

from table import *
from _1 import *
from _2 import *
from _3 import *
from _4 import *
from _4_1 import *
from _4_2 import *
from _4_3 import *
from _5_1 import *
from _5_2 import *
from _6_1 import *
from _6_2 import *
from _6_3 import *
from _7_1 import *
from _7_2 import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.button_check = QtWidgets.QPushButton(self.centralwidget)
        self.button_check.setMinimumSize(QtCore.QSize(93, 0))
        self.button_check.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_check.setFont(font)
        self.button_check.setObjectName("button_check")
        self.horizontalLayout_5.addWidget(self.button_check)
        self.button_table = QtWidgets.QPushButton(self.centralwidget)
        self.button_table.setMinimumSize(QtCore.QSize(93, 0))
        self.button_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_table.setFont(font)
        self.button_table.setObjectName("button_table")
        self.horizontalLayout_5.addWidget(self.button_table)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.layout_request = QtWidgets.QHBoxLayout()
        self.layout_request.setObjectName("layout_request")
        self.layout_left = QtWidgets.QVBoxLayout()
        self.layout_left.setObjectName("layout_left")
        self.layout_1 = QtWidgets.QHBoxLayout()
        self.layout_1.setObjectName("layout_1")
        self.text_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_1.setMinimumSize(QtCore.QSize(281, 51))
        self.text_1.setObjectName("text_1")
        self.layout_1.addWidget(self.text_1)
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setObjectName("button_1")
        self.layout_1.addWidget(self.button_1)
        self.layout_left.addLayout(self.layout_1)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.text_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_2.setMinimumSize(QtCore.QSize(281, 51))
        self.text_2.setObjectName("text_2")
        self.layout_2.addWidget(self.text_2)
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setObjectName("button_2")
        self.layout_2.addWidget(self.button_2)
        self.layout_left.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.text_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_3.setMinimumSize(QtCore.QSize(281, 51))
        self.text_3.setObjectName("text_3")
        self.layout_3.addWidget(self.text_3)
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setObjectName("button_3")
        self.layout_3.addWidget(self.button_3)
        self.layout_left.addLayout(self.layout_3)
        self.layout_4 = QtWidgets.QHBoxLayout()
        self.layout_4.setObjectName("layout_4")
        self.text_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_4.setMinimumSize(QtCore.QSize(281, 51))
        self.text_4.setObjectName("text_4")
        self.layout_4.addWidget(self.text_4)
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setObjectName("button_4")
        self.layout_4.addWidget(self.button_4)
        self.layout_left.addLayout(self.layout_4)
        self.layout_4_1 = QtWidgets.QHBoxLayout()
        self.layout_4_1.setObjectName("layout_4_1")
        self.text_4_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_4_1.setMinimumSize(QtCore.QSize(281, 51))
        self.text_4_1.setObjectName("text_4_1")
        self.layout_4_1.addWidget(self.text_4_1)
        self.button_4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4_1.setObjectName("button_4_1")
        self.layout_4_1.addWidget(self.button_4_1)
        self.layout_left.addLayout(self.layout_4_1)
        self.layout_4_2 = QtWidgets.QHBoxLayout()
        self.layout_4_2.setObjectName("layout_4_2")
        self.text_4_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_4_2.setMinimumSize(QtCore.QSize(281, 51))
        self.text_4_2.setObjectName("text_4_2")
        self.layout_4_2.addWidget(self.text_4_2)
        self.button_4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4_2.setObjectName("button_4_2")
        self.layout_4_2.addWidget(self.button_4_2)
        self.layout_left.addLayout(self.layout_4_2)
        self.layout_4_3 = QtWidgets.QHBoxLayout()
        self.layout_4_3.setObjectName("layout_4_3")
        self.text_4_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_4_3.setMinimumSize(QtCore.QSize(281, 51))
        self.text_4_3.setObjectName("text_4_3")
        self.layout_4_3.addWidget(self.text_4_3)
        self.button_4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4_3.setObjectName("button_4_3")
        self.layout_4_3.addWidget(self.button_4_3)
        self.layout_left.addLayout(self.layout_4_3)
        self.layout_request.addLayout(self.layout_left)
        self.layout_right = QtWidgets.QVBoxLayout()
        self.layout_right.setObjectName("layout_right")
        self.layout_5_1 = QtWidgets.QHBoxLayout()
        self.layout_5_1.setObjectName("layout_5_1")
        self.button_5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5_1.setObjectName("button_5_1")
        self.layout_5_1.addWidget(self.button_5_1)
        self.text_5_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_5_1.setMinimumSize(QtCore.QSize(281, 51))
        self.text_5_1.setObjectName("text_5_1")
        self.layout_5_1.addWidget(self.text_5_1)
        self.layout_right.addLayout(self.layout_5_1)
        self.layout_5_2 = QtWidgets.QHBoxLayout()
        self.layout_5_2.setObjectName("layout_5_2")
        self.button_5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5_2.setObjectName("button_5_2")
        self.layout_5_2.addWidget(self.button_5_2)
        self.text_5_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_5_2.setMinimumSize(QtCore.QSize(281, 51))
        self.text_5_2.setObjectName("text_5_2")
        self.layout_5_2.addWidget(self.text_5_2)
        self.layout_right.addLayout(self.layout_5_2)
        self.layout_6_1 = QtWidgets.QHBoxLayout()
        self.layout_6_1.setObjectName("layout_6_1")
        self.button_6_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6_1.setObjectName("button_6_1")
        self.layout_6_1.addWidget(self.button_6_1)
        self.text_6_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_6_1.setMinimumSize(QtCore.QSize(281, 51))
        self.text_6_1.setObjectName("text_6_1")
        self.layout_6_1.addWidget(self.text_6_1)
        self.layout_right.addLayout(self.layout_6_1)
        self.layout_6_2 = QtWidgets.QHBoxLayout()
        self.layout_6_2.setObjectName("layout_6_2")
        self.button_6_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6_2.setObjectName("button_6_2")
        self.layout_6_2.addWidget(self.button_6_2)
        self.text_6_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_6_2.setMinimumSize(QtCore.QSize(281, 51))
        self.text_6_2.setObjectName("text_6_2")
        self.layout_6_2.addWidget(self.text_6_2)
        self.layout_right.addLayout(self.layout_6_2)
        self.layout_6_3 = QtWidgets.QHBoxLayout()
        self.layout_6_3.setObjectName("layout_6_3")
        self.button_6_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6_3.setObjectName("button_6_3")
        self.layout_6_3.addWidget(self.button_6_3)
        self.text_6_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_6_3.setMinimumSize(QtCore.QSize(281, 51))
        self.text_6_3.setObjectName("text_6_3")
        self.layout_6_3.addWidget(self.text_6_3)
        self.layout_right.addLayout(self.layout_6_3)
        self.layout_7_1 = QtWidgets.QHBoxLayout()
        self.layout_7_1.setObjectName("layout_7_1")
        self.button_7_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7_1.setObjectName("button_7_1")
        self.layout_7_1.addWidget(self.button_7_1)
        self.text_7_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_7_1.setMinimumSize(QtCore.QSize(281, 51))
        self.text_7_1.setObjectName("text_7_1")
        self.layout_7_1.addWidget(self.text_7_1)
        self.layout_right.addLayout(self.layout_7_1)
        self.layout_7_2 = QtWidgets.QHBoxLayout()
        self.layout_7_2.setObjectName("layout_7_2")
        self.button_7_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7_2.setObjectName("button_7_2")
        self.layout_7_2.addWidget(self.button_7_2)
        self.text_7_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_7_2.setMinimumSize(QtCore.QSize(281, 51))
        self.text_7_2.setObjectName("text_7_2")
        self.layout_7_2.addWidget(self.text_7_2)
        self.layout_right.addLayout(self.layout_7_2)
        self.layout_request.addLayout(self.layout_right)
        self.verticalLayout_6.addLayout(self.layout_request)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_table.clicked.connect(self.window_table)
        self.button_1.clicked.connect(self.window_1)
        self.button_2.clicked.connect(self.window_2)
        self.button_3.clicked.connect(self.window_3)
        self.button_4.clicked.connect(self.window_4)
        self.button_4_1.clicked.connect(self.window_4_1)
        self.button_4_2.clicked.connect(self.window_4_2)
        self.button_4_3.clicked.connect(self.window_4_3)
        self.button_5_1.clicked.connect(self.window_5_1)
        self.button_5_2.clicked.connect(self.window_5_2)
        self.button_6_1.clicked.connect(self.window_6_1)
        self.button_6_2.clicked.connect(self.window_6_2)
        self.button_6_3.clicked.connect(self.window_6_3)
        self.button_7_1.clicked.connect(self.window_7_1)
        self.button_7_2.clicked.connect(self.window_7_2)

    def window_table(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_table()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_1()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def window_2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_3()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_4(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_4()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def window_4_1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_4_1()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_4_2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_4_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_4_3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_4_3()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def window_5_1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_5_1()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_5_2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_5_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_6_1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_6_1()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_6_2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_6_2()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def window_6_3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_6_3()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_7_1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_7_1()
        self.ui.setupUi(self.window)
        self.window.show()

    def window_7_2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_7_2()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проект"))
        self.label.setText(_translate("MainWindow", "Проверьте соединение базы данных"))
        self.button_check.setText(_translate("MainWindow", "Проверить подключение"))
        self.button_table.setText(_translate("MainWindow", "Таблицы - ввод и вывод"))
        self.text_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1. Получить данные о распределении пассажирского автотранспорта по маршрутам</span></p></body></html>"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.text_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2. Получить распределение водителей по автомобилям</span></p></body></html>"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.text_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3. Получить данные об автопарке предприятия.</span></p></body></html>"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.text_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4. Получить данные о числе ремонтов и их стоимости для каждого автотранспорта</span></p></body></html>"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.text_4_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4.1. Получить данные о числе ремонтов и их стоимости по конкретной категории автотранспорта</span></p></body></html>"))
        self.button_4_1.setText(_translate("MainWindow", "4.1"))
        self.text_4_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4.2. Получить данные о числе ремонтов и их стоимости по конкретной марки транспорта</span></p></body></html>"))
        self.button_4_2.setText(_translate("MainWindow", "4.2"))
        self.text_4_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4.3. Получить данные о числе ремонтов и их стоимости по выбранному автомобилю</span></p></body></html>"))
        self.button_4_3.setText(_translate("MainWindow", "4.3"))
        self.button_5_1.setText(_translate("MainWindow", "5.1"))
        self.text_5_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5.1. Получить сведения о наличии гаражного хозяйства в целом</span></p></body></html>"))
        self.button_5_2.setText(_translate("MainWindow", "5.2"))
        self.text_5_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5.2. Получить сведения о наличии гаражного хозяйства по каждой категории транспорта</span></p></body></html>"))
        self.button_6_1.setText(_translate("MainWindow", "6.1"))
        self.text_6_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6.1. Получить данные о подчиненности персонала: рабочие - бригадиры</span></p></body></html>"))
        self.button_6_2.setText(_translate("MainWindow", "6.2"))
        self.text_6_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6.2. Получить данные о подчиненности персонала: бригадиры - мастера</span></p></body></html>"))
        self.button_6_3.setText(_translate("MainWindow", "6.3"))
        self.text_6_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6.3. Получить данные о подчиненности персонала: мастера - начальники</span></p></body></html>"))
        self.button_7_1.setText(_translate("MainWindow", "7.1"))
        self.text_7_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">7.1. Получить данные о работах, выполненных указанным специалистом в целом</span></p></body></html>"))
        self.button_7_2.setText(_translate("MainWindow", "7.2"))
        self.text_7_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">7.2. Получить данные о работах, выполненных указанным специалистом по конкретной авто</span></p></body></html>"))

        self.button_check.clicked.connect(self.select_check)

    def select_check(self):
        try:
            dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='orcl') 
            conn = cx_Oracle.connect(user='test', password='111', dsn=dsn_tns) 
            self.label.setText(QtCore.QCoreApplication.translate("MainWindow", "Базы данных подключена"))
            conn.close()
        except:
            self.label.setText(QtCore.QCoreApplication.translate("MainWindow", "Нет соединения с базой данных"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
